ALTER TABLE Users
DROP CONSTRAINT PK_Users
GO

ALTER TABLE Users
ADD PRIMARY KEY (Id)
GO

ALTER TABLE Users
ADD CONSTRAINT UQ_Username UNIQUE (Username)
GO

ALTER TABLE Users
ADD CONSTRAINT CHK_Username CHECK (LEN(Username) > 2)
GO